# yaml-language-server: $schema=settings.schema.yaml
$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #

accounts:
  # Get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=room-booking-local-dev&scopes=users&only_for_me=true
  api_jwt_token: "token"
mongo:
  uri: mongodb://mongoadmin:secret@localhost:27017/db?authSource=admin
base_url: "https://innohassle.ru"
google:
  service_account_file_path: service_account.json
  subject: null
  drive_folder_id: null
